father = input("")
mother = input("")
me = input("")
sister = input("")
brother = input("")
print("your father is " + father + " years old")
print("your father is " + mother + " years old")
print("your father is " + brother + " years old")
print("your father is " + sister + " years old")
print("i am  " + me + " years old")
print("your father will be  " , (int(father) + 20) , " years old in 20 years")
print("your father will be " , (int(mother) + 20) , " years old in 20 years")
print("your father will be " , (int(brother) + 20) , " years old in 20 years")
print("your father will be " , (int(sister) + 20) , " years old in 20 years")
print("you will be  " , (int(me) + 20) , " years old in 20 years")